import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import styles from "./page.module.css"
import Footer from './_components/common/footer/Footer'
import Header from "./_components/common/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{width: '100%', height: '100vh'}}>      
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.body}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
